[package]
name = "dockify"
version = "0.1.0"
authors = ["markzyu <7296488+markzyu@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
executor = {path = "../executor"}
mods = {path = "../mods"}
procfs = {path = "../procfs"}
ptrace = {path = "../ptrace"}
sysaug = {path = "../sysaug"}
clap = "3.0.0-beta.2"
thiserror = "1.0.25"
tracing = "0.1.26"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3.6", features = ["env-filter"] } 
