# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

on: [push, pull_request]

name: Quickstart

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            target: aarch64-unknown-linux-gnu
          - arch: armv7
            target: armv7-unknown-linux-gnueabihf
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target ${{ matrix.target }}
          use-cross: true

# This doesn't work right now. 'cross' cannot simulate spawning new processes
#  test:
#    name: Tests
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        include:
#          - arch: aarch64
#            target: aarch64-unknown-linux-gnu
#          - arch: armv7
#            target: armv7-unknown-linux-gnueabihf
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v2
# 
#      - name: Install stable toolchain
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable
#          override: true
#          target: ${{ matrix.target }}
# 
#      - name: Run cargo test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --all --no-fail-fast --target ${{ matrix.target }}
#          use-cross: true

  lints:
    name: Lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            target: aarch64-unknown-linux-gnu
          - arch: armv7
            target: armv7-unknown-linux-gnueabihf
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
          target: ${{ matrix.target }}

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
          use-cross: true

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ matrix.target }}
          use-cross: true
