[package]
name = "ptrace"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.81"
nix = "0.20.1"
thiserror = "1.0.25"
tracing = "0.1.26"

[dev-dependencies]
ntest = "0.7.2"
